project:
  type: website

website:
  title: "q"
  back-to-top-navigation: true
  
include-in-header: 
  - header.html

resources: img/*

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - styles.scss
    toc: true



